channels:
  - conda-forge
dependencies:
  - black
  - click
  - flake8
  - isort
  - matplotlib
  - omniscidb-cpu
  - pip
  - pytest
  - pre_commit
  - sh
  - pip:
    - seed-isort-config
    - git+https://github.com/ibis-project/ibis.git@master
