version: '3.3'

services:

  omniscidb:
    image: omnisci/core-os-cpu:v4.7.0
    hostname: omniscidb
    ports:
      - 6274:6274
      - 6278:6278
    volumes:
      - ./omniscidb.conf:/omnisci-storage/omnisci.conf
      - ../ibis_benchmark:/opt/ibis_benchmark
    deploy:
      resources:
        limits:
          memory: 4G

  waiter:
    image: jwilder/dockerize
    command: |
      dockerize -wait tcp://omniscidb:6274
                -wait-retry-interval 5s
                -timeout 10m

